import { readFileSync, writeFileSync } from "fs";

const p = "src/content/blogs.json";
const blogs = JSON.parse(readFileSync(p, "utf8"));

/** promo callout appended as last section of every new blog */
const promo = (hi) => ({
  h: { en: "Get Your Free Reading on Hast Rekha AI", hi: "हस्त रेखा AI पर अपनी फ्री रीडिंग पाएँ" },
  p: [
    {
      en: "Ready to see what your own palm says? Visit https://hastrekhaai.online and get a complete free reading — palm lines, rashi, nakshatra and lagna — computed with rule-based Vedic methods, instantly and without sign-up. Try it now at https://hastrekhaai.online.",
      hi: hi || "अपनी हथेली क्या कहती है, जानने को तैयार हैं? https://hastrekhaai.online पर जाएँ और पाएँ संपूर्ण फ्री रीडिंग — हस्तरेखा, राशि, नक्षत्र और लग्न — नियम-आधारित वैदिक विधि से, तुरंत और बिना रजिस्ट्रेशन। अभी विज़िट करें: https://hastrekhaai.online",
    },
  ],
});

const B = (slug, cat, en, hi, exEn, exHi, tagsEn, tagsHi, date, mins, intro, sections) => ({
  slug, cat,
  title: { en, hi },
  excerpt: { en: exEn, hi: exHi },
  tags: { en: tagsEn, hi: tagsHi },
  date, mins,
  intro,
  sections,
  tip: {
    en: "This article is general Vedic guidance, not a substitute for professional advice.",
    hi: "यह लेख सामान्य वैदिक मार्गदर्शन है, पेशेवर सलाह का विकल्प नहीं।",
  },
});

const newBlogs = [
  B("ai-palmistry-future","palm","AI Palmistry in 2026: Can Technology Read Your Destiny?","AI हस्तरेखा 2026: क्या तकनीक भाग्य पढ़ सकती है?","AI is transforming ancient palmistry — from instant line detection to rule-based Vedic engines. Here's how modern tools read your palm, what they get right, and where human intuition still wins.","AI प्राचीन हस्तरेखा को बदल रहा है — तुरंत रेखा-पहचान से लेकर नियम-आधारित वैदिक इंजन तक। जानें आधुनिक टूल्स हाथ कैसे पढ़ते हैं, क्या सही होता है, और कहाँ मानवीय अंतर्ज्ञान अब भी आगे है।",["ai palmistry","hast rekha ai","technology"],["एआई हस्तरेखा","हस्त रेखा एआई","तकनीक"],"2026-09-19",7,
    [{en:"Palmistry is five thousand years old, yet in 2026 it is having a technology moment. AI-powered tools now detect palm lines from a photo in seconds, and rule-based engines turn those measurements into a structured reading. But can a machine really read destiny?",hi:"हस्तरेखा पाँच हज़ार वर्ष पुरानी है, फिर भी 2026 में इसका तकनीक-युग आ गया है। AI-संचालित टूल्स अब फोटो से सेकंडों में रेखाएँ पहचानते हैं, और नियम-आधारित इंजन उन माप से व्यवस्थित रीडिंग बनाते हैं। पर क्या मशीन सचमुच भाग्य पढ़ सकती है?"}],
    [{h:{en:"How AI reads a palm",hi:"AI हाथ कैसे पढ़ता है"},p:[{en:"Modern systems use computer vision to trace the heart, head, life and fate lines, then measure their length, depth and curvature. A rule-based Vedic engine — like the one behind Hast Rekha AI — maps those features to classical Samudrika Shastra interpretations, along with your birth details for the kundli overlay.",hi:"आधुनिक सिस्टम कंप्यूटर-विज़न से हृदय, मस्तिष्क, जीवन और भाग्य रेखाओं को ट्रेस करते हैं, फिर उनकी लंबाई, गहराई व वक्रता मापते हैं। नियम-आधारित वैदिक इंजन — जैसा हस्त रेखा AI के पीछे है — उन विशेषताओं को शास्त्रीय समुद्रिक शास्त्र की व्याख्याओं से जोड़ता है, और जन्म-विवरण से कुंडली ओवरले बनाता है."}]},
     {h:{en:"What AI gets right — and wrong",hi:"AI क्या सही करता है — और क्या गलत"},p:[{en:"AI is excellent at consistency: the same palm always yields the same analysis, with no mood or bias. Where it falls short is nuance — a human palmist reads skin texture, warmth and the seeker's questions. That is why the best approach is hybrid: let the engine do the maths, use the shastra for meaning.",hi:"AI निरंतरता में उत्कृष्ट है: एक ही हाथ से हमेशा एक जैसा विश्लेषण निकलता है, बिना मनोदशा या पक्षपात के। जहाँ ये टूटता है वह सूक्ष्मता है — मानव हस्तरेखी त्वचा की बनावट, ऊष्मा और जिज्ञासु के प्रश्न भी पढ़ता है। इसीलिए सर्वोत्तम उपा�य संकर है: गणित इंजन से कराइए, अर्थ शास्त्र से लीजिए।"}]},
     promo()]
  ),
  B("numerology-palm-combo","graha","Numerology + Palmistry: The Destiny Combo","अंक ज्योतिष + हस्तरेखा: भाग्य का संयोजन","Your birth number and your palm often tell the same story from two directions. Learn how numerology and hast rekha confirm each other — and what it means when they disagree.","आपका जन्म-अंक और आपकी हथेली अक्सर दो दिशाओं से एक ही कथा कहते हैं। जानें अंक ज्योतिष और हस्तरेखा एक-दूसरे की पुष्टि कैसे करते हैं — और असहमति होने पर उसका अर्थ क्या है।",["numerology","palmistry","ank jyotish"],["अंक ज्योतिष","हस्तरेखा","अंक विज्ञान"],"2026-09-18",6,
    [{en:"Numerology reduces your birth date to a single vibration; palmistry reads the map your body carries. When both point the same way, the reading gains real weight.",hi:"अंक ज्योतिष आपकी जन्म-तिथि को एक स्पंदन में घटाता है; हस्तरेखा शरीर के वहन किए नक्शे को पढ़ती है। दोनों एक दिशा में इशारा करें तो रीडिंग का भार सचमुच बढ़ जाता है।"}],
    [{h:{en:"Life number and the fate line",hi:"मूलांक और भाग्य रेखा"},p:[{en:"If your life number (mulank) is 1, 3 or 9 — solar numbers — classical texts expect a strong, unbroken fate line and a prominent Jupiter mount. 2, 7 are lunar: a longer heart line and fuller moon mount fit better. Check both on your own hand at hastrekhaai.online.",hi:"यदि आपका मूलांक 1, 3 या 9 है — सौर अंक — तो शास्त्रों में अटूट भाग्य रेखा और प्रबल गुरु पर्वत अपेक्षित है। 2, 7 चांद्र हैं: लंबी हृदय रेखा और भरा चंद्र पर्वत अधिक मेल खाता है। दोनों अपने हाथ पर hastrekhaai.online पर जाँचें।"}]},
     {h:{en:"When they disagree",hi:"जब दोनों असहमत हों"},p:[{en:"A mismatch is not a contradiction — it is a crossroads. Numerology shows the potential you were born with; the palm shows how much of it your choices have activated. A weak line under a strong number means untapped potential, and upay can help direct it.",hi:"बेमेल विरोध नहीं, चौराहा है। अंक ज्योतिष जन्मजात क्षमता दिखाता है; हाथ बताता है कि आपके निर्णयों ने उसमें से कितना जगाया। प्रबल अंक के नीचे कमजोर रेखा अनुत्तेजित क्षमता है — उपाय उसे दिशा दे सकते हैं।"}]},
     promo()]
  ),
  B("left-hand-right-hand","palm","Left Hand vs Right Hand in Palmistry: Which One Matters?","हस्तरेखा में बायाँ बनाम दायाँ हाथ: कौन-सा मायने रखता है?","The classic debate, settled: the passive hand shows what you were born with, the dominant hand shows what you made of it. Here is how palmists actually read both.","शास्त्रीय बहस का समाधान: स्वाभाविक हाथ वह दिखाता है जो जन्म से मिला, प्रयुक्त हाथ वह जो आपने बनाया। हस्तरेखी दोनों को वास्तव में कैसे पढ़ते हैं, जानिए।",["left hand","right hand","palm reading basics"],["बायाँ हाथ","दायाँ हाथ","हस्तरेखा आधार"],"2026-09-17",5,
    [{en:"Ask any traditional palmist and you will hear the same formula: the hand you do not write with is the inheritance, the one you do is the achievement.",hi:"किसी भी पारंपरिक हस्तरेखी से पूछिए, एक ही सूत्र मिलेगा: जिस हाथ से नहीं लिखते वह विरासत है, जिससे लिखते हैं वह उपलब्धि।"}],
    [{h:{en:"Two hands, two stories",hi:"दो हाथ, दो कथा"},p:[{en:"The passive hand carries sanchita — your accumulated karma and inborn temperament. The active hand carries kriyamana — what you are doing with it right now. Differences between the two are the most interesting part of any reading: they show growth, or drift.",hi:"स्वाभाविक हाथ संचित — जन्मजात स्वभाव व कर्म — वहन करता है। प्रयुक्त हाथ क्रियमाण — वर्तमान उपयोग — दिखाता है। दोनों का अंतर किसी भी रीडिंग का सबसे रोचक हिस्सा है: वही विकास या विचलन दिखाता है।"}]},
     {h:{en:"Practical rules",hi:"व्यावहारिक नियम"},p:[{en:"Read both hands always. If the active hand's life line is stronger, your habits are supporting your health. If the passive hand's heart line is deeper, you have grown guarded. Upload both palms at hastrekhaai.online and compare the two reports side by side.",hi:"सदा दोनों हाथ पढ़ें। प्रयुक्त हाथ की जीवन रेखा अधिक प्रबल हो तो आपकी आदतें स्वास्थ्य के साथ हैं। स्वाभाविक हाथ की हृदय रेखा गहरी हो तो आपने सावधानी अपनाई है। दोनों हथेलियाँ hastrekhaai.online पर अपलोड करें और दोनों रिपोर्ट साथ-साथ तुलना करें।"}]},
     promo()]
  ),
  B("saturn-return-2026","graha","Saturn Return 2026: Why Your Late 20s Feel So Heavy","शनि की वापसी 2026: 20 के अंत का दौर इतना भारी क्यों लगता है","Saturn returns to its birth position roughly every 29 years — and 2026 is a big Saturn year. What this transit asks of you, and the classical upay that soften it.","शनि लगभग हर 29 वर्ष में अपने जन्म-स्थान पर लौटता है — और 2026 बड़ा शनि-वर्ष है। यह गोचर आपसे क्या माँगता है, और शास्त्रीय उपाय जो इसे सुहाते हैं।",["saturn return","shani gochar","transit 2026"],["शनि वापसी","शनि गोचर","गोचर 2026"],"2026-09-16",8,
    [{en:"Between ages 27 and 31, Saturn comes home to where it sat when you were born. Careers wobble, relationships get serious, and everyone suddenly wants a five-year plan. This is not a curse — it is an audit.",hi:"27 से 31 की आयु के बीच शनि अपने जन्म-स्थान पर लौटता है। करियर डगमगाता है, रिश्ते गंभीर होते हैं, और सब पाँच-वर्षीय योजना माँगने लगते हैं। यह शाप नहीं — ऑडिट है।"}],
    [{h:{en:"What Saturn actually audits",hi:"शनि वास्तव में क्या जाँचता है"},p:[{en:"Saturn is the rishi of consequences. Its return tests whatever you built on borrowed foundations — the career chosen for status, the relationship kept out of habit. What survives this transit is genuinely yours; what falls was scaffolding.",hi:"शनि परिणामों के ऋषि हैं। उनकी वापसी उसी की परीक्षा लेती है जो उधार नींव पर खड़ा किया — प्रतिष्ठा के लिए चुना करियर, आदत से निभाया रिश्ता। जो इस गोचर में टिकता है वह सचमुच आपका है; जो गिरता है वह पटड़ी थी।"}]},
     {h:{en:"Classical upay for Shani",hi:"शनि के शास्त्रीय उपाय"},p:[{en:"The tradition prescribes service (especially to elders and labourers), Saturday discipline, sesame-oil lamp on Saturdays, and the Shani mantra 'Om Sham Shanicharaya Namah' — 108 repetitions. Discipline, not fear, is the response Saturn rewards. For your personal Saturn placement, get a free kundli at hastrekhaai.online.",hi:"परंपरा सेवा (विशेषकर वृद्धों व श्रमिकों की), शनिवार-अनुशासन, शनिवार को तिल-तेल का दीप, और शनि मंत्र 'ॐ शं शनैश्चराय नमः' — 108 जप — सुझाती है। शनि अनुशासन को पुरस्कृत करते हैं, भय को नहीं। अपनी शनि-स्थिति के लिए hastrekhaai.online पर मुफ्त कुंडली बनाइए।"}]},
     promo()]
  ),
  B("marriage-line-timing","palm","Marriage Line: When Will You Marry? Reading the Timing","विवाह रेखा: विवाह कब? समय पढ़ने की विधि","Palmists time marriage from the marriage lines on the percussion — position, depth and branches all carry meaning. A practical guide to what the shastra actually says.","हस्तरेखी विवाह-रेखाओं की स्थिति, गहराई व शाखाओं से समय निकालते हैं। शास्त्र वास्तव में क्या कहता है — एक व्यावहारिक मार्गदर्शन।",["marriage line","vivah rekha","marriage timing"],["विवाह रेखा","विवाह समय","हस्तरेखा"],"2026-09-15",6,
    [{en:"The small horizontal lines on the edge of the palm between the heart line and little finger are the marriage lines — and they are the most-asked-about feature in any reading.",hi:"हृदय रेखा और कनिष्ठा के बीच हथेली के किनारे की छोटी आड़ी रेखाएँ विवाह रेखाएँ हैं — और रीडिंग में सबसे अधिक पूछी जाने वाली विशेषता यही हैं।"}],
    [{h:{en:"Position = timing",hi:"स्थिति = समय"},p:[{en:"Classical method: divide the distance from heart line to little-finger base into thirds. A line in the upper third suggests early marriage (before ~25), the middle third around 25–34, and the lower third later in life. Depth shows the strength of the bond; a fork at the start shows a long courtship.",hi:"शास्त्रीय विधि: हृदय रेखा से कनिष्ठा-आधार तक की दूरी को तीन भागों में बाँटिए। ऊपरी तिहाई में रेखा शीघ्र विवाह (~25 से पहले) संकेतित करती है, मध्य तिहाई लगभग 25–34, और निचली तिहाई जीवन का विलंब। गहराई बंधन की मजबूती दिखाती है; आरंभ का काँटा लंबी प्रेम-यात्रा दिखाता है।"}]},
     {h:{en:"What branches and islands mean",hi:"शाखाएँ और द्वीप का अर्थ"},p:[{en:"An upward branch from the marriage line is read as growth through partnership; a downward branch flags a period of strain. An island suggests a phase of separation or ill health of the spouse. Remember — these are tendencies, not verdicts. Check your own lines free at hastrekhaai.online.",hi:"विवाह रेखा से ऊपर की शाखा साझेदारी से विकास पढ़ी जाती है; नीचे की शाखा तनाव-काल दिखाती है। द्वीप जीवनसाथी के स्वास्थ्य या पृथक्काल का संकेत है। स्मरण रहे — ये प्रवृत्तियाँ हैं, निर्णय नहीं। अपनी रेखाएँ hastrekhaai.online पर मुफ्त देखें।"}]},
     promo()]
  ),
  B("mangal-dosh-truth","graha","Mangal Dosh: Myths, Facts and the Real Remedy","मंगल दोष: मिथक, तथ्य और वास्तविक उपाय","Mangal dosh (Kuja dosha) scares more people than it should. What the classical texts actually require, when it truly matters, and the authentic upay.","मंगल दोष (कुज दोष) का डर जितना होना चाहिए, उससे अधिक है। शास्त्र वास्तव में क्या कहते हैं, यह कब महत्वपूर्ण होता है, और प्रामाणिक उपाय क्या है।",["mangal dosh","kuja dosha","marriage astrology"],["मंगल दोष","कुज दोष","विवाह ज्योतिष"],"2026-09-14",7,
    [{en:"Ask 'mangli ho?' in any arranged-marriage conversation and the room changes temperature. But the classical rules for Mangal dosh are far narrower than popular fear suggests.",hi:"अरेंज्ड-मैरिज की किसी भी बातचीत में 'मांगलिक हो?' पूछ दीजिए, कमरा बदल जाता है। पर मंगल दोष के शास्त्रीय नियम लोक-भय की तुलना में बहुत संकुचित हैं।"}],
    [{h:{en:"What actually counts",hi:"वास्तव में क्या गिना जाता है"},p:[{en:"Mangal dosh is considered when Mars sits in the 1st, 4th, 7th, 8th or 12th house from the lagna. But tradition applies many cancellations: Mars in own sign (Aries/Scorpio), Mars aspected by Jupiter, Mars past 28 years of age by dasha, and — most importantly — matching Mangal in both charts neutralises it entirely.",hi:"लग्न से मंगल 1, 4, 7, 8 या 12 भाव में हो तो मंगल दोष माना जाता है। पर परंपरा अनेक परिहार बताती है: मंगल स्वगृही (मेष/वृश्चिक), गुरु की दृष्टि में मंगल, 28 वर्ष से अधिक आयु में दशा-प्रभाव, और — सबसे महत्वपूर्ण — दोनों कुंडलियों में मेल तो दोष पूर्णतः निरस्त।"}]},
     {h:{en:"The real remedy",hi:"वास्तविक उपाय"},p:[{en:"Tuesday Hanuman worship, red lentils donated on Tuesdays, and the mangal mantra 'Om Kram Kreem Kraum Sah Bhaumaya Namah' are the classical prescriptions. But the deepest remedy is matching: get both charts read free at hastrekhaai.online before drawing any conclusion.",hi:"मंगलवार हनुमान उपासना, मंगलवार अरहर-दान, और मंगल मंत्र 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः' — शास्त्रीय उपाय ये हैं। पर सबसे गहरा उपाय मिलान है: कोई निष्कर्ष निकालने से पहले दोनों कुंडलियाँ hastrekhaai.online पर मुफ्त पढ़वाइए।"}]},
     promo()]
  ),
  B("money-lines-palm","palm","Money Lines in Your Palm: The Wealth Signs","हथेली की धन रेखाएँ: संपत्ति के संकेत","From the money triangle to the sun line to Mercury mounts — where classical palmistry looks for wealth signatures, and what a strong one actually promises.","धन त्रिभुज से सूर्य रेखा और बुध पर्वत तक — शास्त्रीय हस्तरेखा संपत्ति के चिह्न कहाँ खोजती है, और प्रबल चिह्न वास्तव में क्या वादा करता है।",["money line","wealth palmistry","dhan rekha"],["धन रेखा","धन हस्तरेखा","संपत्ति संकेत"],"2026-09-13",6,
    [{en:"Wealth in hast rekha is never one line — it is a pattern. The money triangle, the sun line, the Mercury line and the Jupiter mount all contribute to what classical palmists call the 'wealth signature'.",hi:"हस्तरेखा में धन कभी एक रेखा नहीं — पैटर्न है। धन त्रिभुज, सूर्य रेखा, बुध रेखा और गुरु पर्वत मिलकर वह बनाते हैं जिसे शास्त्रीय हस्तरेखी 'धन-हस्ताक्षर' कहते हैं।"}],
    [{h:{en:"The money triangle",hi:"धन त्रिभुज"},p:[{en:"Formed where the head line and life line meet with a third connecting line. A clear, unbroken triangle indicates steady accumulation; breaks suggest money flowing through, not staying. A star on the Apollo line is read as sudden fame-linked fortune.",hi:"जहाँ मस्तिष्क रेखा और जीवन रेखा मिलती हैं और तीसरी जोड़ने वाली रेखा बनती है, वह धन त्रिभुज है। स्पष्ट, अटूट त्रिभुज स्थिर संचय दिखाता है; विच्छेद धन के आना-जाना। अपोलो रेखा पर तारा कीर्ति-संबद्ध अचानक भाग्य पढ़ा जाता है।"}]},
     {h:{en:"Sun line and Mercury line",hi:"सूर्य रेखा और बुध रेखा"},p:[{en:"A deep sun line under the ring finger promises recognition-based prosperity — wealth that follows reputation. A clear Mercury line adds business acumen. Find your wealth signature instantly at hastrekhaai.online with a free palm scan.",hi:"अनामिका के नीचे गहरी सूर्य रेखा प्रतिष्ठा-जन्य समृद्धि का वादा करती है — नाम के पीछे चलता धन। स्पष्ट बुध रेखा व्यापारिक बुद्धि जोड़ती है। अपना धन-हस्ताक्षर hastrekhaai.online पर मुफ्त पाम-स्कैन से तुरंत जानिए।"}]},
     promo()]
  ),
  B("retrograde-planets-2026","graha","Retrograde Planets 2026: What Vakri Grah Really Mean","वक्री ग्रह 2026: रेट्रोग्रेड का वास्तविक अर्थ","Mercury retrograde memes aside, what does vakri actually mean in Jyotish? The real effects on dasha results, plus the 2026 retrograde calendar.","मर्करी रेट्रोग्रेड के मीम्स छोड़िए — ज्योतिष में वक्री का वास्तविक अर्थ क्या है? दशा-फल पर असर, और 2026 का वक्री कैलेंडर।",["retrograde","vakri grah","mercury retrograde 2026"],["वक्री ग्रह","रेट्रोग्रेड 2026","बुध वक्री"],"2026-09-12",7,
    [{en:"Every few months the internet declares Mercury retrograde responsible for everything from lost keys to breakups. Jyotish has a subtler — and more useful — view of vakri planets.",hi:"हर कुछ महीनों में इंटरनेट मर्करी रेट्रोग्रेड को खोई चाबियों से ब्रेकअप तक सबका कारण बताता है। ज्योतिष का वक्री ग्रहों पर दृष्टिकोण सूक्ष्मतर — और अधिक उपयोगी — है।"}],
    [{h:{en:"What vakri means in Jyotish",hi:"ज्योतिष में वक्री का अर्थ"},p:[{en:"A retrograde planet is read as strong (cheshta bala — high effort-motivation) but inward-facing. Its dasha results arrive with revisiting: past projects resurface, old contacts return, unfinished karma demands completion. Retrograde malefics turn their intensity inward — self-doubt, rework.",hi:"वक्री ग्रह बलवान (चेष्टा बल — उच्च प्रयास-ऊर्जा) पर अंतर्मुखी पढ़ा जाता है। उसकी दशा के फल पुनरावृत्ति के साथ आते हैं: पुराने प्रोजेक्ट लौटते हैं, पुराने संपर्क जुड़ते हैं, अधूरा कर्म पूर्णता माँगता है। वक्री पाप ग्रह तीव्रता भीतर मोड़ते हैं — आत्म-संदेह, दोहराव।"}]},
     {h:{en:"Surviving the 2026 retrogrades",hi:"2026 की वक्री अवधि"},p:[{en:"Practical rule: during a retrograde dasha or transit, review rather than launch, reconcile rather than decide. Get your personal dasha calendar free at hastrekhaai.online to see exactly when your vakri periods fall in 2026.",hi:"व्यावहारिक नियम: वक्री दशा या गोचर में शुभारंभ नहीं, समीक्षा; निर्णय नहीं, सुलह। अपनी व्यक्तिगत दशा-कैलेंडर hastrekhaai.online पर मुफ्त देखिए और जानिए 2026 में आपकी वक्री अवधियाँ कब हैं।"}]},
     promo()]
  ),
  B("life-line-longevity-myth","palm","Does a Short Life Line Mean a Short Life? The Myth Busted","छोटी जीवन रेखा का अर्थ कम आयु नहीं — मिथक का खंडन","The most misunderstood line in palmistry. Why length is not lifespan, what the life line actually measures, and what to read instead.","हस्तरेखा की सबसे गलत समझी जाने वाली रेखा। लंबाई आयु क्यों नहीं है, जीवन रेखा वास्तव में क्या मापती है, और इसके बजाय क्या पढ़ें।",["life line","longevity","palm myths"],["जीवन रेखा","आयु","हस्तरेखा मिथक"],"2026-09-11",5,
    [{en:"Nothing frightens a first-time palm-reading client like a short life line. And nothing is further from the classical teaching.",hi:"पहली बार हाथ पढ़वाने वाले को छोटी जीवन रेखा सबसे अधिक डराती है। और शास्त्रीय शिक्षा से उतना दूर और कुछ नहीं।"}],
    [{h:{en:"What the life line measures",hi:"जीवन रेखा क्या मापती है"},p:[{en:"The life line circles the Jupiter mount and Venus mount — it maps vitality, recovery power and life-quality, not years. Classical texts read longevity primarily from the thumb, the overall hand strength and the taurus (thumb base), with the life line as one supporting factor among many.",hi:"जीवन रेखा गुरु पर्वत और शुक्र पर्वत के चारों ओर घेरती है — यह जीवनी, रोग-प्रतिरोध और जीवन-गुणवत्ता का नक्शा है, वर्षों का नहीं। शास्त्र आयु मुख्यतः अंगूठे, समग्र हस्त-बल और कंठ से पढ़ते हैं; जीवन रेखा अनेक सहायक कारकों में एक है।"}]},
     {h:{en:"What actually matters more",hi:"वास्तव में क्या अधिक मायने रखता है"},p:[{en:"A deep, clear, unbroken line of any length beats a long but chained one. Branches upward show achievement; downward ones flag energy drains. Scan your life line free at hastrekhaai.online and read the honest interpretation — not the fear version.",hi:"किसी भी लंबाई की गहरी, स्पष्ट, अटूट रेखा लंबी पर जंजीरयुक्त रेखा से बेहतर है। ऊपर की शाखाएँ उपलब्धि; नीचे की ऊर्जा-हानि। अपनी जीवन रेखा hastrekhaai.online पर मुफ्त स्कैन करें और ईमानदार व्याख्या पढ़ें — डर वाली नहीं।"}]},
     promo()]
  ),
  B("nakshatra-based-naming","rashi","Naming Your Baby by Nakshatra: The 2026 Guide","नक्षत्र से बच्चे का नाम: 2026 मार्गदर्शिका","The classical naming system links each nakshatra pada to a starting syllable. Complete syllable chart, plus how to find your baby's nakshatra in minutes.","शास्त्रीय नामकरण प्रणाली हर नक्षत्र-पद को आरंभिक अक्षर से जोड़ती है। पूर्ण अक्षर-तालिका, और बच्चे का नक्षत्र मिनटों में ज्ञात करने की विधि।",["nakshatra naming","baby names 2026","namakarana"],["नक्षत्र नामकरण","बच्चे के नाम 2026","नामकरण"],"2026-09-10",6,
    [{en:"Namakarana — the naming ceremony — is one of the sixteen samskaras, and the classical method starts from the moon's nakshatra at birth, not from a trending name list.",hi:"नामकरण — षोडश संस्कारों में से एक — की शास्त्रीय विधि ट्रेंडिंग नाम-सूची से नहीं, जन्म के समय चंद्र के नक्षत्र से आरंभ होती है।"}],
    [{h:{en:"How the syllable system works",hi:"अक्षर-प्रणाली कैसे काम करती है"},p:[{en:"Each of the 27 nakshatras has four padas, and each pada maps to a syllable — Ashwini's padas begin चु, चे, चो, ला; Rohini's ओ, वा, वी, वू; and so on. The syllable carries the nakshatra's vibration into daily use. The full 108-syllable chart is built into Hast Rekha AI's kundli output.",hi:"27 नक्षत्रों में से प्रत्येक के चार पद हैं, और हर पद एक अक्षर से जुड़ा है — अश्विनी के पद चु, चे, चो, ला से; रोहिणी के ओ, वा, वी, वू से; आगे इसी प्रकार। अक्षर नक्षत्र का स्पंदन दैनिक उपयोग में वहन करता है। पूर्ण 108-अक्षर तालिका हस्त रेखा AI की कुंडली में निहित है।"}]},
     {h:{en:"Finding the nakshatra fast",hi:"नक्षत्र शीघ्र ज्ञात करें"},p:[{en:"Enter the birth date, time and place at hastrekhaai.online — the engine computes the moon's sidereal longitude and returns the nakshatra, pada and recommended syllables instantly, free. Then pick a modern name starting with that syllable.",hi:"hastrekhaai.online पर जन्म-तिथि, समय और स्थान दर्ज करें — इंजन चंद्र का सायन रेखांश निकालकर नक्षत्र, पद और अनुशंसित अक्षर तुरंत, मुफ्त देता है। फिर उसी अक्षर से आधुनिक नाम चुन लीजिए।"}]},
     promo()]
  ),
  B("mercury-line-career","palm","The Mercury Line: Your Hidden Business Talent","बुध रेखा: आपकी छिपी व्यापारिक प्रतिभा","Rare but powerful — the Mercury line (health line) reveals business instinct, healing ability and communication gifts when present.","दुर्लभ पर प्रभावशाली — बुध रेखा (स्वास्थ्य रेखा) होने पर व्यापार-बुद्धि, चिकित्सा-क्षमता और संवाद-प्रतिभा प्रकट करती है।",["mercury line","business palmistry","health line"],["बुध रेखा","व्यापार हस्तरेखा","स्वास्थ्य रेखा"],"2026-09-09",5,
    [{en:"Most palms don't have a clear Mercury line — and that itself is information. When present, it runs from the life line's base toward the Mercury mount under the little finger.",hi:"अधिकांश हथेलियों में स्पष्ट बुध रेखा नहीं होती — और यही जानकारी है। होने पर यह जीवन रेखा के आधार से कनिष्ठा के नीचे बुध पर्वत की ओर चलती है।"}],
    [{h:{en:"What a strong Mercury line promises",hi:"प्रबल बुध रेखा क्या वादा करती है"},p:[{en:"Classical readings tie it to three gifts: commercial instinct (buying, selling, negotiation), healing hands (medicine, therapy, hospitality) and persuasive communication. Entrepreneurs and doctors alike are found to carry it. A broken line warns of overwork affecting health.",hi:"शास्त्रीय व्याख्या इसे तीन प्रतिभाओं से जोड़ती है: व्यापारिक सूझ (क्रय-विक्रय, सौदेबाजी), चिकित्सक हस्त (चिकित्सा, उपचार, आतिथ्य) और प्रभावी संवाद। उद्यमी और चिकित्सक — दोनों में यह मिलती है। टूटी रेखा अति-श्रम से स्वास्थ्य-प्रभाव की चेतावनी है।"}]},
     {h:{en:"Developing the gift",hi:"प्रतिभा का विकास"},p:[{en:"A faint Mercury line strengthens with use — the shastra links Budha to Vishnu worship on Wednesdays and green moong donations. Check whether you carry this line at hastrekhaai.online — the free scan flags it automatically.",hi:"हल्की बुध रेखा उपयोग से प्रबल होती है — शास्त्र बुध को बुधवार विष्णु-उपासना और हरे मूंग-दान से जोड़ते हैं। जाँचिए कि यह रेखा आपमें है या नहीं — hastrekhaai.online का मुफ्त स्कैन इसे स्वतः दिखाता है।"}]},
     promo()]
  ),
  B("palm-reading-guide-beginners","palm","How to Read Your Own Palm: A 10-Minute Beginner's Method","अपनी हथेली स्वयं कैसे पढ़ें: 10-मिनट की शुरुआती विधि","A structured first reading you can do tonight: hand shape, then the three major lines, then mounts. No jargon, no fear — just the classical order.","आज रात ही कर सकते हैं एक व्यवस्थित पहली रीडिंग: हाथ की बनावट, फिर तीन प्रमुख रेखाएँ, फिर पर्वत। न शब्दजाल, न डर — बस शास्त्रीय क्रम।",["palm reading guide","beginner palmistry","self reading"],["हस्तरेखा गाइड","शुरुआती हस्तरेखा","स्वयं रीडिंग"],"2026-09-08",7,
    [{en:"Professional readings follow an order — shape, lines, mounts, marks — and you can borrow that structure tonight with nothing but good light and ten minutes.",hi:"पेशेवर रीडिंग एक क्रम रखती है — आकार, रेखाएँ, पर्वत, चिह्न — और आप वह ढाँचा आज रात, बस अच्छी रोशनी और दस मिनट में अपना सकते हैं।"}],
    [{h:{en:"Step 1 — hand shape; Step 2 — the three lines",hi:"चरण 1 — हाथ का आकार; चरण 2 — तीन रेखाएँ"},p:[{en:"Earth hands (square, heavy) value stability; air hands (square, long fingers) live in ideas; water hands (oval, soft) feel everything; fire hands (rectangular, short fingers) act fast. Then read the three majors: heart line (feeling style), head line (thinking style), life line (energy style).",hi:"मृदा हस्त (वर्गाकार, भारी) स्थिरता चाहते हैं; वायु हस्त (वर्गाकार, लंबी उँगलियाँ) विचारों में जीते हैं; जल हस्त (अंडाकार, कोमल) सब महसूस करते हैं; अग्नि हस्त (आयताकार, छोटी उँगलियाँ) तुरंत करते हैं। फिर तीन प्रमुख पढ़ें: हृदय रेखा (भाव-शैली), मस्तिष्क रेखा (विचार-शैली), जीवन रेखा (ऊर्जा-शैली)।"}]},
     {h:{en:"Step 3 — mounts and the shortcut",hi:"चरण 3 — पर्वत और शॉर्टकट"},p:[{en:"Press each mount lightly: a springy Jupiter mount shows leadership appetite; a full Venus mount shows warmth and vitality. Or skip the manual work — upload your palm photo at hastrekhaai.online and get all of this analysed free in under a minute.",hi:"हर पर्वत को हल्का दबाइए: स्प्रिंग-जैसा गुरु पर्वत नेतृत्व-लालसा दिखाता है; भरा शुक्र पर्वत ऊष्मा व जीवनी। या मेहनत छोड़िए — hastrekhaai.online पर हथेली की फोटो अपलोड करें और यह सब एक मिनट से कम में मुफ्त विश्लेषण पाएँ।"}]},
     promo()]
  ),
  B("gemini-season-2026-rashi","rashi","Rashi Predictions 2026: The Year's Second Half, Sign by Sign","राशिफल 2026: वर्ष का दूसरा अर्ध, राशि-दर-राशि","Jupiter, Saturn and Rahu shift the second half of 2026 differently for each moon sign. A compact per-rashi outlook — find yours and plan the quarter.","गुरु, शनि और राहु 2026 का दूसरा अर्ध हर चंद्र-राशि के लिए अलग रूप से बदलते हैं। प्रति-राशि संक्षिप्त दृष्टिकोण — अपनी राशि देखें और तिमाही की योजना बनाएँ।",["rashifal 2026","horoscope 2026","rashi predictions"],["राशिफल 2026","भविष्यफल 2026","राशि अनुमान"],"2026-09-07",8,
    [{en:"Half-year outlooks work because the slow planets — Jupiter and Saturn — set the theme while faster ones colour it. Here is the compact 2026-H2 picture per moon sign.",hi:"अर्ध-वार्षिक दृष्टिकोण इसलिए काम करता है कि धीमे ग्रह — गुरु और शनि — विषय-वस्तु तय करते हैं, तीव्र ग्रह उसे रंगते हैं। प्रति चंद्र-राशि 2026-द्वितीयार्ध का संक्षिप्त चित्र यह है।"}],
    [{h:{en:"Fire and earth signs",hi:"अग्नि और मृदा राशियाँ"},p:[{en:"Aries: Jupiter's aspect on career houses favors bold moves after September. Leo: recognition rises but guard the heart-line expenses. Sagittarius: travel and teaching open doors. Taurus: property and family matters finalize. Virgo: health routines finally stick. Capricorn: Saturn's own return tests structures — delegate more.",hi:"मेष: सितंबर के बाद गुरु की करियर-भाव पर दृष्टि साहसिक कदम को अनुकूल। सिंह: मान-वृद्धि पर हृदय-रेखा खर्चों पर रोक। धनु: यात्रा और शिक्षा द्वार खोलेंगे। वृष: संपत्ति व परिवार के प्रश्न निपटेंगे। कन्या: स्वास्थ्य-दिनचर्या अब टिकेगी। मकर: शनि की अपनी वापसी ढाँचे की जाँच लेगी — कार्य बाँटिए।"}]},
     {h:{en:"Air and water signs",hi:"वायु और जल राशियाँ"},p:[{en:"Gemini: Mercury's long stay makes Q4 the year's best for launches. Libra: partnerships get formalized — shaadi or shastra (contracts). Aquarius: research pays; avoid shortcuts. Cancer: home and mother need attention; a gentle upay — white sweets on Mondays. Scorpio: transformation completes; the fog lifts after October. Pisces: guru-blessed travel; give back through teaching.",hi:"मिथुन: बुध का दीर्घ वास चौथी तिमाही को वर्ष का सर्वश्रेष्ठ शुभारंभ-काल बनाता है। तुला: साझेदारी रूप लेगी — विवाह या अनुबंध। कुम्भ: अनुसंधान फलदायी; शॉर्टकट से बचें। कर्क: घर व माता को ध्यान चाहिए; सौम्य उपाय — सोमवार सफेद मिठाई दान। वृश्चिक: परिवर्तन पूर्ण; अक्टूबर के बाद कोहरा उठेगा। मीन: गुरु-अनुग्रह यात्रा; शिक्षण देकर ऋण चुकाएँ।"}]},
     {h:{en:"Get your personal version",hi:"अपना व्यक्तिगत विवरण पाएँ"},p:[{en:"Generic sun-sign lists can only sketch. Your moon's exact nakshatra, lagna and dasha change everything — compute them free at hastrekhaai.online and read your own 2026, not everyone's.",hi:"सामान्य सूर्य-राशि सूची केवल रेखाचित्र है। आपके चंद्र का ठीक नक्षत्र, लग्न और दशा सब बदल देते हैं — hastrekhaai.online पर मुफ्त गणना करें और सबका नहीं, अपना 2026 पढ़ें।"}]},
     promo()]
  ),
  B("simian-line-rare-mark","palm","The Simian Line: One of the Rarest Palm Marks","सिमियन रेखा: हथेली का अत्यंत दुर्लभ चिह्न","When heart and head lines merge into one, you get the simian crease — found in barely 1–3% of hands. What classical palmistry reads into it.","जब हृदय और मस्तिष्क रेखा एक हो जाएँ, तो सिमियन रेखा बनती है — केवल 1–3% हाथों में। शास्त्रीय हस्तरेखा इससे क्या पढ़ती है।",["simian line","rare palm marks","single crease"],["सिमियन रेखा","दुर्लभ हस्त चिह्न","एकल रेखा"],"2026-09-06",5,
    [{en:"Run a finger across your palm: most people feel two creases under the fingers. A few feel one. That single-crease hand — the simian line — is among the rarest features a palmist encounters.",hi:"हथेली पर उँगली फेरिए: अधिकांश लोगों को उँगलियों के नीचे दो रेखाएँ मिलेंगी। कुछ को एक। वह एकल-रेखा वाला हाथ — सिमियन रेखा — हस्तरेखी के सामने आने वाले दुर्लभतम लक्षणों में है।"}],
    [{h:{en:"What it traditionally means",hi:"परंपरागत अर्थ"},p:[{en:"Classical palmistry reads the simian line as fusion of feeling and thinking — the person processes emotion through logic and logic through emotion. The traditional virtues: extraordinary focus and all-or-nothing commitment. The caution: difficulty switching off. It is intensity, never a defect.",hi:"शास्त्रीय हस्तरेखा सिमियन रेखा को भाव और विचार के मेल के रूप में पढ़ती है — ऐसा व्यक्ति भावना को तर्क से और तर्क को भावना से संसाधित करता है। पारंपरिक गुण: असाधारण एकाग्रता और सर्व-या-कुछ नहीं प्रतिबद्धता। सावधानी: बंद करना कठिन। यह तीव्रता है, दोष कदापि नहीं।"}]},
     {h:{en:"Living with intensity",hi:"तीव्रता के साथ जीवन"},p:[{en:"Simian-line holders thrive with one deep pursuit rather than five scattered ones. If you suspect you have this rare line, verify it free at hastrekhaai.online — the analysis detects single-crease hands and adjusts the whole reading accordingly.",hi:"सिमियन रेखा वाले एक गहरी तपस्या में फलते-फूलते हैं, पाँच बिखरी चीज़ों में नहीं। संदेह हो कि यह दुर्लभ रेखा आपमें है — hastrekhaai.online पर मुफ्त जाँचें; विश्लेषण एकल-रेखा पहचानकर पूरी रीडिंग उसी अनुरूप ढालता है।"}]},
     promo()]
  ),
  B("astrology-podcast-trend-2026","upay","India's Astrology Boom 2026: Why Gen Z Is Checking Kundlis Again","भारत का ज्योतिष-उन्माद 2026: जेन Z फिर कुंडली क्यों देख रही है","Short-form astrology reels, nakshatra-based dating and AI kundli apps — the ancient science is trending with 18–25s. What's driving it, and how to engage sanely.","शॉर्ट-फॉर्म ज्योतिष रील्स, नक्षत्र-आधारित डेटिंग और AI कुंडली ऐप्स — प्राचीन विज्ञान 18–25 आयुवर्ग में ट्रेंड कर रहा है। इसके कारण, और संयमित जुड़ाव कैसे हो।",["astrology trend 2026","gen z astrology","kundli app"],["ज्योतिष ट्रेंड 2026","जेन Z ज्योतिष","कुंडली ऐप"],"2026-09-05",6,
    [{en:"Astrology content in India has exploded among Gen Z — but this generation consumes it differently: 30-second reels, AI-generated readings, and nakshatra-compatibility filters on dating apps.",hi:"भारत में ज्योतिष-सामग्री जेन Z के बीच विस्फोटक रूप से फैली है — पर यह पीढ़ी इसे नए ढंग से लेती है: 30-सेकंड रील्स, AI-जनित रीडिंग्स, और डेटिंग ऐप्स पर नक्षत्र-अनुकूलता फ़िल्टर।"}],
    [{h:{en:"What's driving the boom",hi:"उन्माद के पीछे क्या है"},p:[{en:"Three forces: vernacular AI tools made Jyotish accessible in Hindi and regional languages; algorithm feeds reward daily-use formats (raashifal reels); and post-pandemic uncertainty keeps people seeking frameworks. The risk is skimming — depth lost to dopamine.",hi:"तीन शक्तियाँ: देशी-भाषा AI टूल्स ने ज्योतिष को हिंदी-क्षेत्रीय भाषाओं में सुलभ बनाया; एल्गोरिद्म-फ़ीड दैनिक-उपयोग फॉर्मेट (राशिफल रील्स) को पुरस्कृत करते हैं; और महामारी-उत्तर अनिश्चितता ढाँचों की खोज बढ़ाती है। जोखिम है ऊपरी-ऊपर पढ़ना — गहराई स्पंदन-सुख की कीमत पर।"}]},
     {h:{en:"Engaging sanely",hi:"संयमित जुड़ाव"},p:[{en:"Use reels as doorways, not destinations. One structured kundli or palm reading — like the free one at hastrekhaai.online — teaches more than a hundred skimmable clips, because it is computed from your actual birth data. Depth is the trend that never expires.",hi:"रील्स को द्वार बनाइए, गंतव्य नहीं। एक व्यवस्थित कुंडली या हस्तरेखा रीडिंग — जैसी hastrekhaai.online पर मुफ्त मिलती है — सैकड़ों झलकियों से अधिक सिखाती है, क्योंकि वह आपके वास्तविक जन्म-आँकड़ों से गणित होती है। गहराई ही वह ट्रेंड है जो कभी समाप्त नहीं होता।"}]},
     promo()]
  ),
  B("heart-line-relationship-style","palm","Your Heart Line Reveals Your Relationship Style","हृदय रेखा बताती है आपकी रिश्तों की शैली","Curved or straight, long or short, ending under Jupiter or Saturn — the heart line is a map of how you love. Find your type and what it predicts.","वक्र या सीधी, लंबी या छोटी, गुरु या शनि के नीचे समाप्त — हृदय रेखा आपके प्रेम का नक्शा है। अपना प्रकार और उसका अनुमान जानिए।",["heart line","relationship palmistry","love line"],["हृदय रेखा","रिश्ते हस्तरेखा","प्रेम रेखा"],"2026-09-04",5,
    [{en:"The top-most major line on the palm is the heart line — and classical palmistry divides it into distinct types, each describing a relationship style.",hi:"हथेली की सबसे ऊपरी प्रमुख रेखा हृदय रेखा है — और शास्त्रीय हस्तरेखा इसे विशिष्ट प्रकारों में बाँटती है, हर प्रकार एक रिश्ता-शैली वर्णित करता है।"}],
    [{h:{en:"The four classical types",hi:"चार शास्त्रीय प्रकार"},p:[{en:"Curving up to Jupiter: idealistic lover — devoted, expects the same. Ending under Saturn: guarded realist — loyalty shown by acts, not words. Reaching the Mercury side: expressive communicator — needs verbal affection. Short and deep: intense but private. A chained line flags emotional sensitivity; islands, periods of grief.",hi:"गुरु तक ऊपर वक्र: आदर्शवादी प्रेमी — समर्पित, वैसा ही अपेक्षित। शनि के नीचे समाप्त: संयत यथार्थवादी — भक्ति कर्म से, वाणी से नहीं। बुध-पार्श्व तक पहुँचे: भावप्रकाशक संवादी — वाचिक स्नेह अपेक्षित। छोटी व गहरी: तीव्र पर निजी। जंजीरयुक्त रेखा भाव-संवेदनशीलता; द्वीप शोक-काल।"}]},
     {h:{en:"Compatibility short-cuts",hi:"अनुकूलता के शॉर्टकट"},p:[{en:"Jupiter-type with Saturn-type balances beautifully — dreamer and anchor. Two Jupiter-types create romance and chaos together. Check both heart lines free at hastrekhaai.online and get the pair analysis in one report.",hi:"गुरु-प्रकार और शनि-प्रकार का मेल सुंदर संतुलन — स्वप्नद्रष्टा और भार। दो गुरु-प्रकार साथ रोमांच और अराजकता दोनों। दोनों हृदय रेखाएँ hastrekhaai.online पर मुफ्त जाँचें — एक रिपोर्ट में जोड़ी-विश्लेषण पाएँ।"}]},
     promo()]
  ),
  B("rahu-ketu-karmic-axis","graha","Rahu-Ketu: The Karmic Axis Explained Simply","राहु-केतु: कार्मिक अक्ष की सरल व्याख्या","The shadow planets have no body — yet they shape obsession, phobia and liberation more than any visible graha. A clear guide to the Rahu-Ketu axis in your chart.","छाया ग्रहों का शरीर नहीं — फिर भी वे मोह, भय और मोक्ष को किसी दृश्य ग्रह से अधिक आकार देते हैं। आपकी कुंडली में राहु-केतु अक्ष की स्पष्ट मार्गदर्शिका।",["rahu ketu","karmic axis","shadow planets"],["राहु केतु","कार्मिक अक्ष","छाया ग्रह"],"2026-09-03",7,
    [{en:"Every chart has two points that are not planets at all — Rahu, the head of the serpent, and Ketu, its tail. Where they sit is where your soul signed its most unusual contract.",hi:"हर कुंडली में दो बिंदु हैं जो ग्रह बिल्कुल नहीं — राहु, सर्प-शिर, और केतु, सर्प-पुच्छ। जहाँ वे बैठते हैं, वहीं आपकी आत्मा ने अपना सबसे विचित्र अनुबंध किया है।"}],
    [{h:{en:"Rahu: hunger; Ketu: mastery",hi:"राहु: तृष्णा; केतु: निपुणता"},p:[{en:"Rahu's house is where you endlessly want more — recognition, wealth, foreign lands, experience. Ketu's house is where you are already expert but feel detached — past-life mastery that no longer excites. Classical reading: feed Rahu consciously, honour Ketu's gifts without clinging.",hi:"राहु का भाव वहाँ है जहाँ आप अनंत अधिक चाहते हैं — मान, धन, विदेश, अनुभव। केतु का भाव वहाँ जहाँ आप निपुण हैं पर अलग-सा महसूस करते हैं — पूर्वजन्म-कौशल जो अब रुचिकर नहीं। शास्त्रीय पाठ: राहु को सचेत पोषित करें, केतु की देन का सम्मान करें, आसक्त हुए बिना।"}]},
     {h:{en:"Upay for the axis",hi:"अक्ष के उपाय"},p:[{en:"Rahu: coconut donation on Saturdays, 'Om Ram Rahave Namah' 108 times. Ketu: 'Om Kem Ketave Namah', feeding dogs, and keeping a flag in the home shrine. For your exact Rahu-Ketu houses, generate your kundli free at hastrekhaai.online — the axis is computed with Lahiri ayanamsa precision.",hi:"राहु: शनिवार नारियल-दान, 'ॐ रां राहवे नमः' 108 बार। केतु: 'ॐ कें केतवे नमः', कुत्तों को भोजन, घर के पूजा-स्थल में ध्वज। अपने ठीक राहु-केतु भाव हेतु hastrekhaai.online पर मुफ्त कुंडली बनाइए — अक्ष लाहिड़ी अयनांश परिशुद्धता से गणित होता है।"}]},
     promo()]
  ),
];

const existing = new Set(blogs.map((b) => b.slug));
let added = 0;
for (const nb of newBlogs) {
  if (!existing.has(nb.slug)) { blogs.push(nb); added++; }
}
writeFileSync(p, JSON.stringify(blogs, null, 1));
console.log("added:", added, "total:", blogs.length);
